-- CreateTable
CREATE TABLE "BayEvent" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "bayId" INTEGER NOT NULL,
    "zoneId" INTEGER NOT NULL,
    "eventType" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BayEvent_bayId_fkey" FOREIGN KEY ("bayId") REFERENCES "ParkingBay" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "BayEvent_zoneId_fkey" FOREIGN KEY ("zoneId") REFERENCES "ParkingZone" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
